### PR TITLE
Replace depracted container by getContainer

### PR DESCRIPTION
**Pull request by ismail1432**
Replace depracted container by getContainer

### CODE REVIEW

**Comment by art-cg** [comment]
I was running into the same problem before. The problem is that getContainer is not available in Symfony 5.4.
The solution could be a BC Layer (do not know how to implement it yet) or stay with the deprecated version. (i guess the problem will arise again with symfony 6 support)

5.4 https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php => static::getContainer() available
4.4 https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php => only static::$container available

**Comment by mtarld** [comment]
Yes, that could be great! We can do this for now and dropping it when dropping Symfony 4.4 support

**Comment by ismail1432** [comment]
I think we can just keep $container for the moment (it's Ok to have deprecated code in code base) and we replace by getContainer when we drop the symfony 4.4 support.

My 2 cents

**Comment by Chris53897** [comment]
That is an valid approach and totally understandable.
End of Support for 4.4 is November 2022/23. https://symfony.com/releases
I hate to code for 4.4 in bundles. Because it is hard to use latest features, support symfony 6 and handle 4.4.
It woul be interesting to know if $container is working in symfony 6. (and removed only in symfony 7)

**Comment by mtarld** [comment]
I'm still thinking of dropping Symfony 4.4 in the first major version of that bundle. 
But for the moment, let's try to fix it as it's only two classes to add (see #67) :slightly_smiling_face:

**Comment by mtarld** [comment]
Superseded by https://github.com/mtarld/api-platform-ms-bundle/pull/67, I'm gonna close it
Many thanks, @ismail1432!

**Pull request closed without merging**
